\LoadClass{article}
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{custom}
\RequirePackage{fontspec}
\RequirePackage{polyglossia}

\setmainfont{FiraGO}
\setmainlanguage{russian}
\setotherlanguages{english}


%% \newfontfamily\cyrillicfont{FiraGO}[Script=Cyrillic]
%% Doesn't help with the cyrillic script problem:

%% This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/W32TeX) (preloaded format=xelatex 2019.10.21)  28 OCT 2019 19:20
%% entering extended mode
%%  restricted \write18 enabled.
%%  %&-line parsing enabled.
%% **ht.tex
%% (./ht.tex
%% LaTeX2e <2018-12-01>
%% (c:/texlive/texmf-local/tex/latex/local/custom.cls
%% (c:/texlive/2019/texmf-dist/tex/latex/base/article.cls
%% ! Package polyglossia Error: The current roman font does not contain the Cyrill
%% ic script!
%% (polyglossia)                Please define \cyrillicfont with \newfontfamily.

%% l.36 Напишите функцию \texttt{square}
%%                                       (квадрат), принимающую аргумент \textt...

%% ? X
